# Generated by Django 2.2.5 on 2021-08-03 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0002_userprofileinformation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfileInformation',
        ),
    ]
